swagger: "2.0"
info: 
  title: "Social Media Aggregator - Security API"
  description: "Security stuff."
consumes:
  - application/json
produces: 
  - application/json
host: 127.0.0.1:9000
basePath: 127.0.0.1:9000