swagger: "2.0"
info: 
  title: "Social Media Aggregator - Post API"
  description: "Posts stuff."
consumes:
  - application/json
produces: 
  - application/json
host: 127.0.0.1:9002
basePath: 127.0.0.1:9002