swagger: "2.0"
info: 
  title: "Social Media Aggregator - User API"
  description: "Users stuff."
consumes:
  - application/json
produces: 
  - application/json
host: 127.0.0.1:9001
basePath: 127.0.0.1:9001